### PR TITLE
Improvements for the Calling an API sample.

### PR DESCRIPTION
**Pull request by saltukalakus**
1- FIX: The requests to the API server weren't sent to the localhost:3001 as the API URL wasn't propagated to **ExternalApi** component.

2-Moved the API server file to ApiServer.js to make the intent more clear. 

PS: As a further refactoring idea we can likely remove **server.js** file for both of the samples as they aren't necessary for app to run in debug mode. I presume we are keeping it for the production builds right now but this file has the potential to confuse novice developers.

### CODE REVIEW

**Comment by saltukalakus** [comment]
Hi @stevehobbsdev sorry fo the late reply. 

> The API URL is just hard-coded as /api/external without the full URL. The ExternalApi component tries to hit the API at http://localhost:3000/api/external which gets proxied through. Could you expand on the core issue here?

In the current implementation /api/external isn't a true external API. Current solution uses the proxy command in the config.json which is actually only for the development mode whereby the react build can't run together with other APIs on the same port during testing. That is due to how react-scripts works. More details are in [this link](https://create-react-app.dev/docs/proxying-api-requests-in-development/).

Once I implemented the "real" independent API, I had the need to propagate the external API URL. And also I had to modify the API server for CORS.

If this makes sense, I can also work on the docker file. In that case please let me know. I can't promise for docs and other SDKs though.

**Comment by stevehobbsdev** [comment]
@saltukalakus This is the part I'm not fully understanding, maybe we can have a Zoom about it when you have time:

> the react build can't run together with other APIs on the same port during testing.

The API doesn't run on the same port, that's the point of the proxy. The React app and the API run on two different ports, and the React app is configured to proxy anything for `/api` to the API.

It's just a little confusing as I haven't had any of these issues while developing the sample or since and I'm not sure why you're getting these issues now. I've had a look at the link you mentioned and it basically describes what we're doing right now.

At the end of the day, we can make the changes but we cannot pull this in until the samples and docs are aligned. I don't mind who does the work but unfortunately we have other higher priority work which must be done first. I would love to understand this problem first though ☝️ so that we're not making changes unnecessarily.

**Comment by saltukalakus** [comment]
Hi @stevehobbsdev sorry for not being clear. Let me try to explain what I have understood. We can have a call of course if you prefer.

In a production built of react project, an API and the bundled file can be served on the same port. However, once we try this on the debug mode, it doesn't work. That is because the **react-scripts** magically bundles the files and servers them on its own and doesn't know how to forward the API requests on the same port to an API server. So, the React team likely added the proxy feature so that the react-scripts can now forward the API calls running on the same port to another port for that application to run on the debug mode.

The API on our sample application is currently running [on the same port](https://github.com/auth0-samples/auth0-react-samples/blob/fee18099017074baa0bb121cfc99fd3fbbe8d4f2/02-Calling-an-API/src/views/ExternalApi.js#L15) where we use the proxy feature so that the **react-scripts** forwards the API requests but this isn't correctly representing an external API. As our sample should likely be showing a sample for an external API call which runs on a different port/domain, my PR makes this possible.

**Comment by stevehobbsdev** [comment]
@saltukalakus Ok I think I understand the issue. There's nothing wrong with the running of the sample but it's not really representative of how access tokens should be used. The API should be running on a different port to represent a different API which is distinct from the React app, and should be called as such by using a fully-qualified URL without the proxy.

In that case I agree with the changes, although `cors` should probably be configured to lock it down to only accept requests from the host the React app is running on.

The other consideration which makes me hesitant is that this technique is used across all our SPA quickstarts, not just the React one. It would make sense to update them all to this best practise. Considering the amount of documentation to update, and the fact that we are about to do another iteration based on the SPA quickstarts and samples based on user research and feedback, it would make sense to roll your feedback into that process. Especially if you don't have the capacity to update the documentation (for React) as part of this.

Instead, I propose we record the feedback in our internal backlog and bring these changes in when we redo these samples again, which is hopefully not in the distant future. We already have a group of issues collected together to go through samples and quickstarts and improve them; this would slot in there nicely.

What do you think?

**Comment by saltukalakus** [comment]
Hi @stevehobbsdev absolutely that is fine with me. I had did this work as part of a team offsite. It isn't coming from a prospect or customer. Thank you so much for reviewing it. I agree that CORS should not allow everything, I had implemented like that to solve the issue quickly before the offsite.

**Comment by stevehobbsdev** [comment]
Thanks for helping me work through this @saltukalakus! I'll close this for now and record the work internally 👍

**Pull request closed without merging**
