### PR TITLE
updated the 03-Calling-an-API README.md. Added in the link to the scr…

### PR DESCRIPTION
**Pull request by kurtzilla**
…eencast as well as providing instructions for creating the Auth0 API

### CODE REVIEW

**Comment by kurtzilla** [comment]
I added a few things from our issue thread to the README.md for the 03-Calling-an-API project.
This may be helpful for beginners.

**Comment by chenkie** [comment]
Thanks @kurtzilla, nice additions.

Out of curiosity, how did you end up finding these samples? The steps for setting up a new API are outlined in the [documentation](https://auth0.com/docs/quickstart/spa/react/03-calling-an-api) associated with this sample.

Thanks

**Comment by kurtzilla** [comment]
I just followed along with the screencast. I now realize I forgot to add the part about adding in a read:messages scope.

I think it would be very helpful to include the documentation link from above as well. 

Let me give it another go to be more complete...brb

**Comment by kurtzilla** [comment]
This latest version is more complete.

**Pull request merged**
